databaseChangeLog:

  - changeSet:
      id: 1
      author: agus.suhardii@gmail.com

  - include:
      file: ddl/20230625_init product.sql
      relativeToChangelogFile: true

  - include:
      file: ddl/20230628_init cart.sql
      relativeToChangelogFile: true

